import React, { useEffect } from "react";
import { useLocation } from "react-router-dom";
import { Divider } from "rsuite";

export default function CSE(){
    const location = useLocation();
    // console.log(location);

    useEffect(() => {
        const element = document.getElementById(location.hash.substring(1));
        if(element){
            element.scrollIntoView({behavior: 'smooth'});
        }
    },[location])

    return(
        <div>
            <div className='markdown'>
                <h1 className='page-heading'>Khoa khoa học và kỹ thuật máy tính</h1>
                <p>Tài liệu đại cương, tài liệu chuyên ngành ...</p>
                <Divider />
            </div>
            <h4 id = 'cs'>Khoa học máy tính</h4>
            <p>
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
            </p>
            <h4 id = 'ce'>Kỹ thuật máy tính</h4>
            <p>
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
                Mình không phải người theo đạo Thiên Chúa, nhưng theo dòng người tấp nập háo hức mong chờ đến Giáng sinh, dường như mình cũng cảm thấy đây là một ngày mang đến những điều hạnh phúc, vui tươi, là dịp để chụp lại những khoảnh khắc lung linh bên cây thông mang không khí tưng bừng, sáng sủa giữa tiết trời mùa đông lành lạnh. Chẳng có ngày Giáng sinh nào giống nhau cả, mỗi năm, ngày này luôn mang đến một điều gì mới mẻ, có lẽ là trong những món quà, trong những lời chúc, hay trong sự mới mẻ và niềm yêu thương đến từ chính những người thân bên mình trong dịp lễ này.
                Ngày sinh nhật mình trùng hợp thay lại chính là dịp Noel. Những năm này, ở tuổi đang dần học cách trưởng thành, ngày sinh nhật hay cũng chính là dịp Giáng sinh vừa cho mình cảm nhận được niềm vui của một ngày lễ ấm cúng và hạnh phúc, cũng như sự lo lắng chênh vênh về những dự định và ước mơ của bản thân khi bước sang tuổi mới, sang năm mới. Năm nay, ngày Giáng sinh, hay ngày sinh nhật mình, là ngày sát gần với kì thi cuối học kì I đầy cam go… Ban đầu khi chợt nghĩ, mình bỗng thấy tủi thân. Vào ngày đặc biệt như thế này mà lại chẳng thể cùng bạn bè và gia đình đi chơi, đi chụp hình hay tận hưởng không khí Giáng sinh nhộn nhịp. Vậy nhưng ngày hôm nay, với những lời chúc mừng của gia đình và bạn bè, mình bỗng thấy cảm động vô cùng vì những tình cảm và sự quan tâm mà mình luôn nhận được. Có lẽ dù chẳng cần làm một điều gì đặc biệt, thì ngày này đối với mình vẫn tràn đầy niềm vui và hạnh phúc biết bao. Nhìn những cây thông Giáng sinh được trang trí lấp lánh trong các của hàng dọc những con phố, lòng mình bỗng cảm nhận được một sự nôn nao và thiêng liêng đến lạ kì. Trong đêm Noel kỳ diệu này, có khi nào những lời ước mong và cầu chúc sẽ trở thành hiện thực hay không?
                Thời gian thi cuối kì sắp đến gần và hẳn là lòng ai cũng phấp phỏm lo lắng không thôi, bản thân mình cũng thế, bởi kì thi này sẽ gần như quyết định những nỗ lực trong cả một học kì qua của mình. Nhưng việc gì đến cũng sẽ đến, quan trọng là chúng ta đã nỗ lực và cố gắng hết sức mình để khi nhìn lại thời gian một năm trôi qua sẽ không phải hối tiếc. Trong đêm Giáng sinh đầy phép nhiệm màu này, mình mong rằng không chỉ bản thân mình, mà mọi người ai cũng sẽ đạt được những điều mình mong muốn, những lời cầu nguyện đẹp đẽ sẽ trở thành hiện thực. Mình cùng DOMEDI xin gửi những lời chúc tốt lành nhất đến với mọi người, chúc mọi người một Giáng sinh thật an lành và vui vẻ!
            </p>
        </div>
    );
}